# Generated by Django 6.0 on 2026-01-25 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_repository_organization_alter_repository_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='pulls_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RepositoryCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('write', 'Write'), ('read', 'Read')], max_length=10)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='repository.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('repository', 'user')},
            },
        ),
    ]
