# Generated by Django 6.0 on 2026-01-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_repository_pulls_count_repository_stars_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
