# Generated by Django 6.0 on 2026-02-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_repository_last_pushed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
