# Generated by Django 6.0 on 2026-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_repository_official'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='official',
        ),
        migrations.AddField(
            model_name='repository',
            name='badge',
            field=models.CharField(choices=[('OFFICIAL', 'Docker Official Image'), ('VERIFIED', 'Verified Publisher'), ('SPONSORED', 'Sponsored OSS'), ('NONE', 'None')], db_index=True, default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_pushed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, max_length=10),
        ),
    ]
