# Generated by Django 6.0 on 2026-02-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
