# Generated by Django 6.0 on 2026-02-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_repository',
            field=models.BooleanField(default=True),
        ),
    ]
