# Generated by Django 6.0 on 2026-01-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pull',
            old_name='created_at',
            new_name='pulled_at',
        ),
        migrations.AlterUniqueTogether(
            name='pull',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pull',
            name='user',
        ),
    ]
