# Generated by Django 6.0 on 2026-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='compressed_size_mb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag',
            name='digest',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='os_arch',
            field=models.CharField(default='linux/amd64', max_length=50),
        ),
    ]
