# Generated by Django 6.0 on 2026-01-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_compressed_size_mb_tag_digest_tag_os_arch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
